# Generated by Django 4.2 on 2024-02-02 17:23

from django.db import migrations, models
import helpers.media_upload


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to=helpers.media_upload.upload_events)),
            ],
        ),
    ]
