# Generated by Django 5.0.1 on 2024-01-31 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_baritem_slug_menuitem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='baritem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_items', to='menu.barcategory'),
        ),
    ]
