# Generated by Django 5.0.1 on 2024-01-31 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_barcategory_alter_baritem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bar_category_items', to='menu.category'),
            preserve_default=False,
        ),
    ]
