# Generated by Django 4.2 on 2024-02-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_hookah_alter_baritem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baritem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
    ]
