# Generated by Django 5.0.1 on 2024-02-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='start_date',
        ),
    ]
