# Generated by Django 4.2 on 2024-02-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_date_reservation_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
    ]
